// Generated by scripts/prepare-images.mjs.
import asset0 from '../assets/journal/about-catch-closeup-480.3d77447a6e45.webp?url';
import asset1 from '../assets/journal/about-catch-closeup-960.cc9184c0ee50.webp?url';
import asset2 from '../assets/journal/about-catch-closeup-1600.0fcc3a3295dd.webp?url';
import asset3 from '../assets/journal/about-pale-ash-480.8e19e7e91917.webp?url';
import asset4 from '../assets/journal/about-pale-ash-960.8013371719ee.webp?url';
import asset5 from '../assets/journal/about-pale-ash-1024.a2a6f8631e1f.webp?url';
import asset6 from '../assets/journal/about-river-portrait-480.4972390c4bd5.webp?url';
import asset7 from '../assets/journal/about-river-portrait-960.1f24093f4b8e.webp?url';
import asset8 from '../assets/journal/about-river-portrait-1494.4bd3e3fb05e8.webp?url';
import asset9 from '../assets/journal/about-walnut-480.12de742e17ef.webp?url';
import asset10 from '../assets/journal/about-walnut-960.8ca807e6a312.webp?url';
import asset11 from '../assets/journal/about-walnut-1024.328f74683019.webp?url';
import asset12 from '../assets/journal/about-woodland-portrait-480.469b6d7ff071.webp?url';
import asset13 from '../assets/journal/about-woodland-portrait-960.e74ad9063e69.webp?url';
import asset14 from '../assets/journal/about-woodland-portrait-1067.254db79ba877.webp?url';
import asset15 from '../assets/journal/catches-baijia-480.3fc60f4b1da1.webp?url';
import asset16 from '../assets/journal/catches-baijia-960.0efe58635d82.webp?url';
import asset17 from '../assets/journal/catches-baijia-1600.fc1e2e3832f3.webp?url';
import asset18 from '../assets/journal/catches-bangui-480.dc0f0d7d84ed.webp?url';
import asset19 from '../assets/journal/catches-bangui-960.b689d20a273b.webp?url';
import asset20 from '../assets/journal/catches-bangui-1600.0892ef1e1ded.webp?url';
import asset21 from '../assets/journal/catches-char-0855-480.59cc92c77310.webp?url';
import asset22 from '../assets/journal/catches-char-0855-960.b5151a61c9f7.webp?url';
import asset23 from '../assets/journal/catches-char-0855-1600.c6b4051797d1.webp?url';
import asset24 from '../assets/journal/catches-char-480.f5dd56525acf.webp?url';
import asset25 from '../assets/journal/catches-char-960.68feb31a5045.webp?url';
import asset26 from '../assets/journal/catches-char-1080.b410ccb6c9dc.webp?url';
import asset27 from '../assets/journal/catches-grayling-5345-480.664a21fd7ca6.webp?url';
import asset28 from '../assets/journal/catches-grayling-5345-960.649313d09466.webp?url';
import asset29 from '../assets/journal/catches-grayling-5345-1600.103e6510b2d4.webp?url';
import asset30 from '../assets/journal/catches-prenanti-0983-480.3a00d31541f2.webp?url';
import asset31 from '../assets/journal/catches-prenanti-0983-960.6ec9f339897b.webp?url';
import asset32 from '../assets/journal/catches-prenanti-0983-1600.5de7de008489.webp?url';
import asset33 from '../assets/journal/catches-qingbo-3845-480.bc0c4082e833.webp?url';
import asset34 from '../assets/journal/catches-qingbo-3845-960.11a2626fca03.webp?url';
import asset35 from '../assets/journal/catches-qingbo-3845-1600.55cc6b281926.webp?url';
import asset36 from '../assets/journal/catches-qingbo-detail-480.5d4bdc2e1e03.webp?url';
import asset37 from '../assets/journal/catches-qingbo-detail-960.1b22e0d93610.webp?url';
import asset38 from '../assets/journal/catches-qingbo-detail-1600.be94a764e38d.webp?url';
import asset39 from '../assets/journal/catches-qingbo-480.8bcc550a13f6.webp?url';
import asset40 from '../assets/journal/catches-qingbo-960.65645be8952c.webp?url';
import asset41 from '../assets/journal/catches-qingbo-1600.5d7679a723c1.webp?url';
import asset42 from '../assets/journal/catches-redeye-5073-480.0039ca639a3c.webp?url';
import asset43 from '../assets/journal/catches-redeye-5073-960.d5b700555563.webp?url';
import asset44 from '../assets/journal/catches-redeye-5073-1080.04d8aa4e8fcc.webp?url';
import asset45 from '../assets/journal/catches-redeye-5082-480.51786bd18998.webp?url';
import asset46 from '../assets/journal/catches-redeye-5082-960.61da7e1aad02.webp?url';
import asset47 from '../assets/journal/catches-redeye-5082-1600.9c61b0821ee0.webp?url';
import asset48 from '../assets/journal/catches-redeye-5103-480.d40c2be75158.webp?url';
import asset49 from '../assets/journal/catches-redeye-5103-960.e0c27f00710e.webp?url';
import asset50 from '../assets/journal/catches-redeye-5103-1080.bcd7fbe2d592.webp?url';
import asset51 from '../assets/journal/catches-schizothorax-0967-480.ab8e4d90d3ba.webp?url';
import asset52 from '../assets/journal/catches-schizothorax-0967-960.94e5ce48a3ec.webp?url';
import asset53 from '../assets/journal/catches-schizothorax-0967-1600.dd38b61fbc5c.webp?url';
import asset54 from '../assets/journal/catches-whitearmor-3827-480.7ed1a282da60.webp?url';
import asset55 from '../assets/journal/catches-whitearmor-3827-960.6ba082815a35.webp?url';
import asset56 from '../assets/journal/catches-whitearmor-3827-1080.78b1dddd32f3.webp?url';
import asset57 from '../assets/journal/catches-whitearmor-3829-480.f99395d80625.webp?url';
import asset58 from '../assets/journal/catches-whitearmor-3829-960.3cf62e61f1a9.webp?url';
import asset59 from '../assets/journal/catches-whitearmor-3829-1080.c04790f983ef.webp?url';
import asset60 from '../assets/journal/catches-yuanwengu-480.4988b0a7d552.webp?url';
import asset61 from '../assets/journal/catches-yuanwengu-960.262a8278d041.webp?url';
import asset62 from '../assets/journal/catches-yuanwengu-1600.c14b764f8e2c.webp?url';
import asset63 from '../assets/journal/hero-dawn-terrain-960.a1473e6d2609.webp?url';
import asset64 from '../assets/journal/hero-dawn-terrain-1536.cf1f8df00535.webp?url';
import asset65 from '../assets/journal/hero-day-terrain-960.b0b806c597d9.webp?url';
import asset66 from '../assets/journal/hero-day-terrain-1536.776224c229f1.webp?url';
import asset67 from '../assets/journal/hero-foreground-960.f9ce87c6c65e.webp?url';
import asset68 from '../assets/journal/hero-foreground-1536.a6b137753552.webp?url';
import asset69 from '../assets/journal/hero-night-terrain-960.586d619855f4.webp?url';
import asset70 from '../assets/journal/hero-night-terrain-1536.a32e0a273a7f.webp?url';
import asset71 from '../assets/journal/hero-terrain-960.e146bb48b5fc.webp?url';
import asset72 from '../assets/journal/hero-terrain-1536.c3f36f84a274.webp?url';
import asset73 from '../assets/journal/hero-zeo-angler-160.7873a3540c17.webp?url';
import asset74 from '../assets/journal/hero-zeo-angler-320.f8d02b4e5afa.webp?url';
import asset75 from '../assets/journal/hero-zeo-cast-backcast-160.a2bbae86ff0c.webp?url';
import asset76 from '../assets/journal/hero-zeo-cast-backcast-320.52028d6b9626.webp?url';
import asset77 from '../assets/journal/hero-zeo-cast-forward-160.3656b7e4ad5e.webp?url';
import asset78 from '../assets/journal/hero-zeo-cast-forward-320.73a6dbc354f6.webp?url';
import asset79 from '../assets/journal/hero-zeo-cast-lift-160.536d2f72b34f.webp?url';
import asset80 from '../assets/journal/hero-zeo-cast-lift-320.d634f47e8652.webp?url';
import asset81 from '../assets/journal/hero-zeo-cast-lookback-v2-160.5784367028fd.webp?url';
import asset82 from '../assets/journal/hero-zeo-cast-lookback-v2-320.590443cbfb1c.webp?url';
import asset83 from '../assets/journal/hero-zeo-cast-lookback-160.8ddcc2e6e54c.webp?url';
import asset84 from '../assets/journal/hero-zeo-cast-lookback-320.66133147e62a.webp?url';
import asset85 from '../assets/journal/fish-icons-ayu-320.74a0832656f1.webp?url';
import asset86 from '../assets/journal/fish-icons-ayu-640.737b7b47c9d4.webp?url';
import asset87 from '../assets/journal/fish-icons-bamboo-320.9b100e9e340f.webp?url';
import asset88 from '../assets/journal/fish-icons-bamboo-640.6bfd40f0f3b0.webp?url';
import asset89 from '../assets/journal/fish-icons-barbel-320.464eebbe7884.webp?url';
import asset90 from '../assets/journal/fish-icons-barbel-640.dfe53ddb764c.webp?url';
import asset91 from '../assets/journal/fish-icons-char-320.dc02f38c8e66.webp?url';
import asset92 from '../assets/journal/fish-icons-char-640.33d5b1ca5b26.webp?url';
import asset93 from '../assets/journal/fish-icons-grayling-320.5a2b28c71a59.webp?url';
import asset94 from '../assets/journal/fish-icons-grayling-640.cc6ee813a4c5.webp?url';
import asset95 from '../assets/journal/fish-icons-gt-320.ff8f1c695f2b.webp?url';
import asset96 from '../assets/journal/fish-icons-gt-640.beaa744b023d.webp?url';
import asset97 from '../assets/journal/fish-icons-gudgeon-v2-320.9372802e7eb3.webp?url';
import asset98 from '../assets/journal/fish-icons-gudgeon-v2-640.c1f47e11cb7a.webp?url';
import asset99 from '../assets/journal/fish-icons-gudgeon-320.22dad287f1c8.webp?url';
import asset100 from '../assets/journal/fish-icons-gudgeon-640.017e8103731e.webp?url';
import asset101 from '../assets/journal/fish-icons-lenok-320.2939fe2e1508.webp?url';
import asset102 from '../assets/journal/fish-icons-lenok-640.c4fff93a41e4.webp?url';
import asset103 from '../assets/journal/fish-icons-mandarin-320.782492e36378.webp?url';
import asset104 from '../assets/journal/fish-icons-mandarin-640.db036e0519ef.webp?url';
import asset105 from '../assets/journal/fish-icons-prenanti-v2-320.bca4b37de4e4.webp?url';
import asset106 from '../assets/journal/fish-icons-prenanti-v2-640.4dd542ed6dca.webp?url';
import asset107 from '../assets/journal/fish-icons-prenanti-320.add7b6181bc2.webp?url';
import asset108 from '../assets/journal/fish-icons-prenanti-640.88b2874df099.webp?url';
import asset109 from '../assets/journal/fish-icons-redeye-320.f27e47a3f7eb.webp?url';
import asset110 from '../assets/journal/fish-icons-redeye-640.313130acdce2.webp?url';
import asset111 from '../assets/journal/fish-icons-schizothorax-320.e2b97f589d87.webp?url';
import asset112 from '../assets/journal/fish-icons-schizothorax-640.d30ac279c3c4.webp?url';
import asset113 from '../assets/journal/fish-icons-steelhead-320.2e844b72c271.webp?url';
import asset114 from '../assets/journal/fish-icons-steelhead-640.c3842c91713a.webp?url';
import asset115 from '../assets/journal/fish-icons-whitearmor-320.2fca021e2039.webp?url';
import asset116 from '../assets/journal/fish-icons-whitearmor-640.e9ddbfbf963a.webp?url';
import asset117 from '../assets/journal/fish-icons-yellowcheek-320.be7c063f64e9.webp?url';
import asset118 from '../assets/journal/fish-icons-yellowcheek-640.54111e950b65.webp?url';
import asset119 from '../assets/journal/simulator-640.2b545a22e8bf.webp?url';
import asset120 from '../assets/journal/simulator-1024.212d19201c9a.webp?url';
import asset121 from '../assets/journal/simulator-1536.408be148eaf6.webp?url';
import asset122 from '../assets/journal/reflection-terrain.c466a41e1c42.webp?url';
import asset123 from '../assets/journal/reflection-day-terrain.90ac8f0e7f99.webp?url';
import asset124 from '../assets/journal/reflection-dawn-terrain.d9cf1a5390ba.webp?url';
import asset125 from '../assets/journal/reflection-night-terrain.3cedcd9139e4.webp?url';
const images = {
  "/images/about/catch-closeup.webp": {
    "width": 1600,
    "height": 900,
    "variants": [
      {
        "width": 480,
        "src": asset0
      },
      {
        "width": 960,
        "src": asset1
      },
      {
        "width": 1600,
        "src": asset2
      }
    ]
  },
  "/images/about/pale-ash.webp": {
    "width": 1024,
    "height": 1024,
    "variants": [
      {
        "width": 480,
        "src": asset3
      },
      {
        "width": 960,
        "src": asset4
      },
      {
        "width": 1024,
        "src": asset5
      }
    ]
  },
  "/images/about/river-portrait.webp": {
    "width": 1494,
    "height": 1600,
    "variants": [
      {
        "width": 480,
        "src": asset6
      },
      {
        "width": 960,
        "src": asset7
      },
      {
        "width": 1494,
        "src": asset8
      }
    ]
  },
  "/images/about/walnut.webp": {
    "width": 1024,
    "height": 1024,
    "variants": [
      {
        "width": 480,
        "src": asset9
      },
      {
        "width": 960,
        "src": asset10
      },
      {
        "width": 1024,
        "src": asset11
      }
    ]
  },
  "/images/about/woodland-portrait.webp": {
    "width": 1067,
    "height": 1600,
    "variants": [
      {
        "width": 480,
        "src": asset12
      },
      {
        "width": 960,
        "src": asset13
      },
      {
        "width": 1067,
        "src": asset14
      }
    ]
  },
  "/images/catches/baijia.webp": {
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 480,
        "src": asset15
      },
      {
        "width": 960,
        "src": asset16
      },
      {
        "width": 1600,
        "src": asset17
      }
    ]
  },
  "/images/catches/bangui.webp": {
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 480,
        "src": asset18
      },
      {
        "width": 960,
        "src": asset19
      },
      {
        "width": 1600,
        "src": asset20
      }
    ]
  },
  "/images/catches/char-0855.webp": {
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 480,
        "src": asset21
      },
      {
        "width": 960,
        "src": asset22
      },
      {
        "width": 1600,
        "src": asset23
      }
    ]
  },
  "/images/catches/char.webp": {
    "width": 1080,
    "height": 1440,
    "variants": [
      {
        "width": 480,
        "src": asset24
      },
      {
        "width": 960,
        "src": asset25
      },
      {
        "width": 1080,
        "src": asset26
      }
    ]
  },
  "/images/catches/grayling-5345.webp": {
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 480,
        "src": asset27
      },
      {
        "width": 960,
        "src": asset28
      },
      {
        "width": 1600,
        "src": asset29
      }
    ]
  },
  "/images/catches/prenanti-0983.webp": {
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 480,
        "src": asset30
      },
      {
        "width": 960,
        "src": asset31
      },
      {
        "width": 1600,
        "src": asset32
      }
    ]
  },
  "/images/catches/qingbo-3845.webp": {
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 480,
        "src": asset33
      },
      {
        "width": 960,
        "src": asset34
      },
      {
        "width": 1600,
        "src": asset35
      }
    ]
  },
  "/images/catches/qingbo-detail.webp": {
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 480,
        "src": asset36
      },
      {
        "width": 960,
        "src": asset37
      },
      {
        "width": 1600,
        "src": asset38
      }
    ]
  },
  "/images/catches/qingbo.webp": {
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 480,
        "src": asset39
      },
      {
        "width": 960,
        "src": asset40
      },
      {
        "width": 1600,
        "src": asset41
      }
    ]
  },
  "/images/catches/redeye-5073.webp": {
    "width": 1080,
    "height": 1920,
    "variants": [
      {
        "width": 480,
        "src": asset42
      },
      {
        "width": 960,
        "src": asset43
      },
      {
        "width": 1080,
        "src": asset44
      }
    ]
  },
  "/images/catches/redeye-5082.webp": {
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 480,
        "src": asset45
      },
      {
        "width": 960,
        "src": asset46
      },
      {
        "width": 1600,
        "src": asset47
      }
    ]
  },
  "/images/catches/redeye-5103.webp": {
    "width": 1080,
    "height": 1920,
    "variants": [
      {
        "width": 480,
        "src": asset48
      },
      {
        "width": 960,
        "src": asset49
      },
      {
        "width": 1080,
        "src": asset50
      }
    ]
  },
  "/images/catches/schizothorax-0967.webp": {
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 480,
        "src": asset51
      },
      {
        "width": 960,
        "src": asset52
      },
      {
        "width": 1600,
        "src": asset53
      }
    ]
  },
  "/images/catches/whitearmor-3827.webp": {
    "width": 1080,
    "height": 1920,
    "variants": [
      {
        "width": 480,
        "src": asset54
      },
      {
        "width": 960,
        "src": asset55
      },
      {
        "width": 1080,
        "src": asset56
      }
    ]
  },
  "/images/catches/whitearmor-3829.webp": {
    "width": 1080,
    "height": 1920,
    "variants": [
      {
        "width": 480,
        "src": asset57
      },
      {
        "width": 960,
        "src": asset58
      },
      {
        "width": 1080,
        "src": asset59
      }
    ]
  },
  "/images/catches/yuanwengu.webp": {
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 480,
        "src": asset60
      },
      {
        "width": 960,
        "src": asset61
      },
      {
        "width": 1600,
        "src": asset62
      }
    ]
  },
  "/images/hero/dawn-terrain.webp": {
    "width": 1536,
    "height": 1024,
    "variants": [
      {
        "width": 960,
        "src": asset63
      },
      {
        "width": 1536,
        "src": asset64
      }
    ]
  },
  "/images/hero/day-terrain.webp": {
    "width": 1536,
    "height": 1024,
    "variants": [
      {
        "width": 960,
        "src": asset65
      },
      {
        "width": 1536,
        "src": asset66
      }
    ]
  },
  "/images/hero/foreground.webp": {
    "width": 1536,
    "height": 1024,
    "variants": [
      {
        "width": 960,
        "src": asset67
      },
      {
        "width": 1536,
        "src": asset68
      }
    ]
  },
  "/images/hero/night-terrain.webp": {
    "width": 1536,
    "height": 1024,
    "variants": [
      {
        "width": 960,
        "src": asset69
      },
      {
        "width": 1536,
        "src": asset70
      }
    ]
  },
  "/images/hero/terrain.webp": {
    "width": 1536,
    "height": 1024,
    "variants": [
      {
        "width": 960,
        "src": asset71
      },
      {
        "width": 1536,
        "src": asset72
      }
    ]
  },
  "/images/hero/zeo-angler.webp": {
    "width": 640,
    "height": 640,
    "variants": [
      {
        "width": 160,
        "src": asset73
      },
      {
        "width": 320,
        "src": asset74
      }
    ]
  },
  "/images/hero/zeo-cast-backcast.webp": {
    "width": 640,
    "height": 640,
    "variants": [
      {
        "width": 160,
        "src": asset75
      },
      {
        "width": 320,
        "src": asset76
      }
    ]
  },
  "/images/hero/zeo-cast-forward.webp": {
    "width": 640,
    "height": 640,
    "variants": [
      {
        "width": 160,
        "src": asset77
      },
      {
        "width": 320,
        "src": asset78
      }
    ]
  },
  "/images/hero/zeo-cast-lift.webp": {
    "width": 640,
    "height": 640,
    "variants": [
      {
        "width": 160,
        "src": asset79
      },
      {
        "width": 320,
        "src": asset80
      }
    ]
  },
  "/images/hero/zeo-cast-lookback-v2.webp": {
    "width": 640,
    "height": 640,
    "variants": [
      {
        "width": 160,
        "src": asset81
      },
      {
        "width": 320,
        "src": asset82
      }
    ]
  },
  "/images/hero/zeo-cast-lookback.webp": {
    "width": 640,
    "height": 640,
    "variants": [
      {
        "width": 160,
        "src": asset83
      },
      {
        "width": 320,
        "src": asset84
      }
    ]
  },
  "/images/fish-icons/ayu.webp": {
    "width": 640,
    "height": 256,
    "variants": [
      {
        "width": 320,
        "src": asset85
      },
      {
        "width": 640,
        "src": asset86
      }
    ]
  },
  "/images/fish-icons/bamboo.webp": {
    "width": 640,
    "height": 320,
    "variants": [
      {
        "width": 320,
        "src": asset87
      },
      {
        "width": 640,
        "src": asset88
      }
    ]
  },
  "/images/fish-icons/barbel.webp": {
    "width": 640,
    "height": 427,
    "variants": [
      {
        "width": 320,
        "src": asset89
      },
      {
        "width": 640,
        "src": asset90
      }
    ]
  },
  "/images/fish-icons/char.webp": {
    "width": 640,
    "height": 640,
    "variants": [
      {
        "width": 320,
        "src": asset91
      },
      {
        "width": 640,
        "src": asset92
      }
    ]
  },
  "/images/fish-icons/grayling.webp": {
    "width": 640,
    "height": 640,
    "variants": [
      {
        "width": 320,
        "src": asset93
      },
      {
        "width": 640,
        "src": asset94
      }
    ]
  },
  "/images/fish-icons/gt.webp": {
    "width": 640,
    "height": 320,
    "variants": [
      {
        "width": 320,
        "src": asset95
      },
      {
        "width": 640,
        "src": asset96
      }
    ]
  },
  "/images/fish-icons/gudgeon-v2.webp": {
    "width": 640,
    "height": 640,
    "variants": [
      {
        "width": 320,
        "src": asset97
      },
      {
        "width": 640,
        "src": asset98
      }
    ]
  },
  "/images/fish-icons/gudgeon.webp": {
    "width": 640,
    "height": 640,
    "variants": [
      {
        "width": 320,
        "src": asset99
      },
      {
        "width": 640,
        "src": asset100
      }
    ]
  },
  "/images/fish-icons/lenok.webp": {
    "width": 640,
    "height": 427,
    "variants": [
      {
        "width": 320,
        "src": asset101
      },
      {
        "width": 640,
        "src": asset102
      }
    ]
  },
  "/images/fish-icons/mandarin.webp": {
    "width": 640,
    "height": 427,
    "variants": [
      {
        "width": 320,
        "src": asset103
      },
      {
        "width": 640,
        "src": asset104
      }
    ]
  },
  "/images/fish-icons/prenanti-v2.webp": {
    "width": 640,
    "height": 640,
    "variants": [
      {
        "width": 320,
        "src": asset105
      },
      {
        "width": 640,
        "src": asset106
      }
    ]
  },
  "/images/fish-icons/prenanti.webp": {
    "width": 640,
    "height": 640,
    "variants": [
      {
        "width": 320,
        "src": asset107
      },
      {
        "width": 640,
        "src": asset108
      }
    ]
  },
  "/images/fish-icons/redeye.webp": {
    "width": 640,
    "height": 427,
    "variants": [
      {
        "width": 320,
        "src": asset109
      },
      {
        "width": 640,
        "src": asset110
      }
    ]
  },
  "/images/fish-icons/schizothorax.webp": {
    "width": 640,
    "height": 320,
    "variants": [
      {
        "width": 320,
        "src": asset111
      },
      {
        "width": 640,
        "src": asset112
      }
    ]
  },
  "/images/fish-icons/steelhead.webp": {
    "width": 640,
    "height": 427,
    "variants": [
      {
        "width": 320,
        "src": asset113
      },
      {
        "width": 640,
        "src": asset114
      }
    ]
  },
  "/images/fish-icons/whitearmor.webp": {
    "width": 640,
    "height": 427,
    "variants": [
      {
        "width": 320,
        "src": asset115
      },
      {
        "width": 640,
        "src": asset116
      }
    ]
  },
  "/images/fish-icons/yellowcheek.webp": {
    "width": 640,
    "height": 320,
    "variants": [
      {
        "width": 320,
        "src": asset117
      },
      {
        "width": 640,
        "src": asset118
      }
    ]
  },
  "/images/river-studio-entry.webp": {
    "width": 1536,
    "height": 1024,
    "variants": [
      {
        "width": 640,
        "src": asset119
      },
      {
        "width": 1024,
        "src": asset120
      },
      {
        "width": 1536,
        "src": asset121
      }
    ]
  },
  "/images/hero/reflection-terrain.webp": {
    "width": 1536,
    "height": 1024,
    "variants": [
      {
        "width": 1536,
        "src": asset122
      }
    ]
  },
  "/images/hero/reflection-day-terrain.webp": {
    "width": 1536,
    "height": 1024,
    "variants": [
      {
        "width": 1536,
        "src": asset123
      }
    ]
  },
  "/images/hero/reflection-dawn-terrain.webp": {
    "width": 1536,
    "height": 1024,
    "variants": [
      {
        "width": 1536,
        "src": asset124
      }
    ]
  },
  "/images/hero/reflection-night-terrain.webp": {
    "width": 1536,
    "height": 1024,
    "variants": [
      {
        "width": 1536,
        "src": asset125
      }
    ]
  }
};
export default images;
