"""Subset the pinned Fontsource font to this site's Chinese text.
Install fonttools[woff]==4.59.1, then run this script from the website root.
Generated fonts are committed; Railway does not need Python.
"""
from pathlib import Path
import re, json
from fontTools.ttLib import TTFont
from fontTools import subset

root = Path(__file__).resolve().parent.parent
chars = set()
for folder in ('app', 'components', 'content'):
    for path in (root / folder).rglob('*'):
        if path.suffix in ('.ts', '.tsx'):
            chars.update(ord(c) for c in path.read_text() if ord(c) > 255)
source = root / 'node_modules/@fontsource-variable/noto-serif-sc'
dest = root / 'app/fonts'
dest.mkdir(exist_ok=True)
css, covered = [], set()
for block in (source / 'wght.css').read_text().split('@font-face')[1:]:
    match = re.search(r'url\(\./files/([^)]*)\)', block)
    if not match:
        continue
    font = TTFont(source / 'files' / match[1])
    # Respect Fontsource's declared ranges, including any overlapping cmap entries.
    ranges = re.search(r'unicode-range: ([^;]+)', block)[1]
    declared = set()
    for item in ranges.split(','):
        ends = item.strip()[2:].split('-')
        declared.update(range(int(ends[0], 16), int(ends[-1], 16) + 1))
    wanted = chars & declared & set(font.getBestCmap())
    if not wanted:
        continue
    options = subset.Options()
    options.flavor = 'woff2'
    sub = subset.Subsetter(options=options)
    sub.populate(unicodes=wanted)
    sub.subset(font)
    name = match[1].replace('.woff2', '-site.woff2')
    font.save(dest / name)
    covered.update(wanted)
    css.append("@font-face { font-family: 'Noto Serif SC Variable'; font-style: normal; font-display: swap; font-weight: 200 900; src: url('./fonts/%s') format('woff2'); unicode-range: %s; }" % (name, ','.join('U+%X' % c for c in sorted(wanted))))
(root / 'app/site-fonts.css').write_text('/* Generated by scripts/prepare-fonts.py. */\n' + '\n'.join(css) + '\n')
(dest / 'coverage.json').write_text(json.dumps(sorted(covered)) + '\n')
print('Subset fonts:', len(css), 'files,', sum(p.stat().st_size for p in dest.glob('*.woff2')), 'bytes')
