// Run after changing source images. Originals remain available for future edits.
import sharp from 'sharp';
import { readdir, mkdir, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { basename } from 'node:path';

const out = 'assets/journal';
await mkdir(out, { recursive: true });
const manifest = {};
async function save(name, buffer) {
  const hash = createHash('sha256').update(buffer).digest('hex').slice(0, 12);
  const path = `${out}/${name}.${hash}.webp`;
  await writeFile(path, buffer);
  return `../${path}`;
}
for (const dir of ['about', 'catches', 'hero', 'fish-icons']) {
  for (const file of await readdir(`public/images/${dir}`)) {
    if (!file.endsWith('.webp')) continue;
    const src = `/images/${dir}/${file}`;
    const meta = await sharp(`public${src}`).metadata();
    const widths = dir === 'hero' ? (file.startsWith('zeo-') ? [160, 320] : [960, 1536])
      : dir === 'fish-icons' ? [320, 640] : [480, 960, 1600];
    const variants = [];
    for (const width of new Set(widths.map(w => Math.min(w, meta.width)))) {
      const buffer = await sharp(`public${src}`).resize({ width }).webp({ quality: dir === 'fish-icons' ? 84 : 78, effort: 6 }).toBuffer();
      variants.push({ width, src: await save(`${dir}-${basename(file, '.webp')}-${width}`, buffer) });
    }
    manifest[src] = { width: meta.width, height: meta.height, variants };
  }
}
const entry = '/images/river-studio-entry.webp';
const variants = [];
for (const width of [640, 1024, 1536]) {
  variants.push({ width, src: await save(`simulator-${width}`, await sharp(`public${entry}`).resize({ width }).webp({ quality: 78, effort: 6 }).toBuffer()) });
}
manifest[entry] = { width: 1536, height: 1024, variants };
const oak = await sharp('public/images/materials/smoked-oak.png').resize(520, 520).webp({ quality: 82, effort: 6 }).toBuffer();
const horizontal = await save('oak-horizontal', oak);
const vertical = await save('oak-vertical', await sharp(oak).rotate(90).webp({ quality: 82, effort: 6 }).toBuffer());
await writeFile('app/materials.css', `/* Generated by scripts/prepare-images.mjs. */\n.frame-rail { background-image: url('${horizontal}'); }\n.frame-rail-left, .frame-rail-right { background-image: url('${vertical}'); }\n`);
// Bake the same softly masked water light once instead of filtering a full-screen
// SVG on every animation frame. Mobile CSS keeps this optional layer unloaded.
const mask = Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="1536" height="1024"><defs><filter id="soft"><feGaussianBlur stdDeviation="9"/></filter></defs><g filter="url(#soft)" fill="white"><path d="M1260 446H1536V1024H1270L1120 920 1290 850 1170 792 1280 729 1330 664 1450 606 1370 548 1310 505Z"/><path d="M350 529C590 535 441 557 529 581S652 620 460 657 192 704 355 741 721 753 828 808 971 887 1190 944" fill="none" stroke="white" stroke-width="24"/></g></svg>`);
for (const file of ['terrain', 'day-terrain', 'dawn-terrain', 'night-terrain']) {
  const image = await sharp(`public/images/hero/${file}.webp`).resize(1536, 1024)
    .modulate({ brightness: 1.13 }).composite([{ input: mask, blend: 'dest-in' }])
    .webp({ quality: 76, effort: 6 }).toBuffer();
  manifest[`/images/hero/reflection-${file}.webp`] = { width: 1536, height: 1024, variants: [{ width: 1536, src: await save(`reflection-${file}`, image) }] };
}
const sources = [...new Set(Object.values(manifest).flatMap(image => image.variants.map(item => item.src)))];
let data = JSON.stringify(manifest, null, 2);
sources.forEach((src, index) => { data = data.replaceAll(JSON.stringify(src), `asset${index}`); });
await writeFile('content/responsive-images.ts', '// Generated by scripts/prepare-images.mjs.\n' +
  sources.map((src, index) => `import asset${index} from '${src}?url';`).join('\n') +
  `\nconst images = ${data};\nexport default images;\n`);
console.log(`Prepared ${Object.keys(manifest).length} responsive images; oak ${oak.length} bytes.`);
